/* Escolhendo um Banco de Dados */
USE
	EMPRESA
GO


/* Programas são unidades que podem ser chamadas de bloco anônimos.
Blocos anônimos não recebem nome, pois não são salvos nol banco.
Criamos blocos anônimos quando iremos executa-los uma só vez ou testar algo. */


/* Bloco de Execução */
BEGIN
	PRINT 'PRIMEIRO BLOCO'
END
GO


/* Blocos de Atribuição de Variáveis */
DECLARE
	@CONTADOR INT
BEGIN
	SET @CONTADOR = 5
	PRINT @CONTADOR
END
GO


/* No SQL Server cada coluna, variável ou local, expressão e parâmetro tem um tipo */
DECLARE
	@V_NUMERO NUMERIC(10,2) = 100.52,
	@V_DATA DATETIME = '20170207'
BEGIN
	PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
	PRINT 'VALOR NMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
	PRINT 'VALOR DATA: ' + CAST(@V_DATA AS VARCHAR)
	PRINT 'VALOR DATA: ' + CONVERT(VARCHAR, @V_DATA, 121)
	PRINT 'VALOR DATA: ' + CONVERT(VARCHAR, @V_DATA, 120)
	PRINT 'VALOR DATA: ' + CONVERT(VARCHAR, @V_DATA, 105)
END
GO


/* Criando Tabela */
CREATE TABLE CARROS (
	CARRO VARCHAR(20),
	FABRICANTE VARCHAR(30)
)
GO


/* Inserindo Dados na Tabela */
INSERT INTO
	CARROS
VALUES (
	'KA',
	'FORD'
)


INSERT INTO
	CARROS
VALUES (
	'FIESTA',
	'FORD'
)


INSERT INTO
	CARROS
VALUES (
	'PRISMA',
	'FORD'
)


INSERT INTO
	CARROS
VALUES (
	'CLIO',
	'RENAULT'
)


INSERT INTO
	CARROS
VALUES (
	'SANDERO',
	'RENAULT'
)


INSERT INTO
	CARROS
VALUES (
	'CHEVETE', 
	'CHEVROLET'
)


INSERT INTO
	CARROS
VALUES (
	'OMEGA',
	'CHEVROLET'
)


INSERT INTO
	CARROS
VALUES (
	'PALIO',
	'FIAT'
)


INSERT INTO
	CARROS
VALUES (
	'DOBLO',
	'FIAT'
)


INSERT INTO
	CARROS
VALUES (
	'UNO',
	'FIAT'
)


INSERT INTO
	CARROS
VALUES (
	'GOL',
	'VOLKSWAGEM'
)
GO


/* Declarando uma Variável */
DECLARE
	@V_CONT_FORD INT,
	@V_CONT_FIAT INT
BEGIN
	--METODO 1 - O SELECT PRECISA RETORNAR UMA SIMPLES COLUNA
	--E UM SO RESULTADO
	SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS
	WHERE FABRICANTE = 'FORD')

	PRINT 'QUANTIDADE FORD: ' + CAST(@V_CONT_FORD AS VARCHAR)

	--METODO 2
	SELECT @V_CONT_FIAT = COUNT(*) FROM CARROS WHERE FABRICANTE = 'FIAT'

	PRINT 'QUANTIDADE FIAT: ' + CONVERT(VARCHAR, @V_CONT_FIAT)
END
GO


/* Blocos If e Else */
DECLARE
	@NUMERO INT = 5
BEGIN
	IF @NUMERO = 5 --EXPRESSAO BOOLEANA - TRUE
		PRINT 'O VALOR É VERDADEIRO'
	ELSE
		PRINT 'O VALOR É FALSO'
END
GO


/* Case */
DECLARE
	@CONTADOR INT
BEGIN
	SELECT
	CASE --O CASE REPRESENTA UMA COLUNA
		WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
		WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
		ELSE 'OUTRAS FAIXAS'
	END AS INFORMACOES,
	*
	FROM CARROS
END
GO


/* Loops While */
DECLARE
	@I INT = 1
BEGIN
	WHILE (@I <15)
	BEGIN
		PRINT 'VALOR DE @I: ' + CAST(@I AS VARCHAR)
		SET @I = @I + 1
	END
END
GO